# Hatchet Query Language Examples

This notebook provides examples for the new Hatchet query language. This feature is not currently in a full release. However, it is now on the `develop` branch of the [LLNL/hatchet repo](https://github.com/LLNL/hatchet).

To install a version of Hatchet that has the query language, use the following commands:

```bash
$ git clone https://github.com/LLNL/hatchet.git
$ cd hatchet
$ python setup.py bdist_wheel
$ python -m pip install [--user] -U dist/hatchet-1.1.0-py3-none-any.whl 
# Replace the whl file with the actual name of your whl file in dist
```

## Hatchet Query Language APIs

The new Hatchet query language has two APIs: a high-level one and a low-level one.

In both of these APIs, the user provides a path of nodes to search for to the `GraphFrame.filter` function. This function will search the GraphFrame for all paths/subtrees that match the user-provided query, and it will return a new GraphFrame containing all these matches.

### High-Level API:

In the high-level API, the user specifies the search path using standard Python data structures. The path itself is represented as a list. Each element of the list represents a node in the query path. Each of these elements can be represented either in a long form or a short form:

#### Long Form:

A long form node is represented as a tuple containing two elements:
1. A "wildcard specifier". This can be one of the following:
  1. A string with value ".", "+", or "\*". These values have the same meaning as they do in regex.
    * "." => Match a single node
    * "+" => Match 1 or more nodes
    * "\*" => Match 0 or more nodes.
  2. A positive integer. This means the query node will match that number of actual GraphFrame nodes.
2. A filter. Filters in the high-level API are represented by Python dictionaries in which keys match a node attribute (column label in the DataFrame). Accepted value fields vary depending on the data type of the node attribute.
  * If the attribute is a string, the filter value is a regex-compatible string (see [Python's re module](https://docs.python.org/3/library/re.html) for more info).
  * If the attribute is a Real number, the filter value can be either
    * A Real Number. In this case, the filter will check the corresponding attribute for equivalence.
    * A String starting with a valid Python numeric comparison operator. In this case, the filter will apply the attribute's value to the comparison. For example, if the filter is "> 5", the query will match when the attribute has a value greater than 5.

#### Short Form:

A short form node can be represented in one of two ways:
1. A wildcard (see the wildcard section of the long form description). In this case, the filter is a catch-all (matches every node).
  * Expands to (wildcard, {}).
2. A filter (see the filter section of the long form description). In this case, only a single node is matched.
  * Expands to (".", filter).
  
### Low-Level API:

The low-level API uses fluent design and lambdas to give the user more fine-tuned control than the high-level API. The first step when using the low-level API is creating a new `hatchet.QueryMatcher` object. After that, the user uses the following two methods to add nodes to the search path:
* `QueryMatcher.match`: Reset the search path and add a new starting node.
* `QueryMatcher.rel`: Add a new node to the query.

Both of these functions accept two arguments:
* A wildcard (default = ".", see the wildcard section of the long-form description above for more info)
* A filter (default = `lambda row: True`). Low-level API filters are callables that accept a single argument (either a Pandas Series or DataFrame) and returns a boolean.
  * If the GraphFrame's `drop_index_levels` was called before the `filter` function is called, the callable will get a Pandas Series. Otherwise, it will receive a Pandas DataFrame.

In [1]:
# import sys
# sys.path.append("/g/g19/brink2/git_root_pub/hatchet-fresh")
# /Users/katywilliams/GitHub/hatchet-katy/hatchet/
import hatchet as ht

# Examples

The rest of this notebook contains example queries and descriptions of these queries.

## Basic Mock Example

This basic example uses a mock GraphFrame taken from the testing directory in the Hatchet repo.

### Generate and Visualize Mock GraphFrame

In [2]:
# Copied from hatchet/hatchet/tests/conftest.py
def mock_graph_literal():
    graph_dict = [
        {
            "name": "foo",
            "metrics": {"time (inc)": 130.0, "time": 0.0},
            "children": [
                {
                    "name": "bar",
                    "metrics": {"time (inc)": 20.0, "time": 5.0},
                    "children": [
                        {"name": "baz", "metrics": {"time (inc)": 5.0, "time": 5.0}},
                        {
                            "name": "grault",
                            "metrics": {"time (inc)": 10.0, "time": 10.0},
                        },
                    ],
                },
                {
                    "name": "qux",
                    "metrics": {"time (inc)": 60.0, "time": 0.0},
                    "children": [
                        {
                            "name": "quux",
                            "metrics": {"time (inc)": 60.0, "time": 5.0},
                            "children": [
                                {
                                    "name": "corge",
                                    "metrics": {"time (inc)": 55.0, "time": 10.0},
                                    "children": [
                                        {
                                            "name": "bar",
                                            "metrics": {
                                                "time (inc)": 20.0,
                                                "time": 5.0,
                                            },
                                            "children": [
                                                {
                                                    "name": "baz",
                                                    "metrics": {
                                                        "time (inc)": 5.0,
                                                        "time": 5.0,
                                                    },
                                                },
                                                {
                                                    "name": "grault",
                                                    "metrics": {
                                                        "time (inc)": 10.0,
                                                        "time": 10.0,
                                                    },
                                                },
                                            ],
                                        },
                                        {
                                            "name": "grault",
                                            "metrics": {
                                                "time (inc)": 10.0,
                                                "time": 10.0,
                                            },
                                        },
                                        {
                                            "name": "garply",
                                            "metrics": {
                                                "time (inc)": 15.0,
                                                "time": 15.0,
                                            },
                                        },
                                    ],
                                }
                            ],
                        }
                    ],
                },
                {
                    "name": "waldo",
                    "metrics": {"time (inc)": 50.0, "time": 0.0},
                    "children": [
                        {
                            "name": "fred",
                            "metrics": {"time (inc)": 35.0, "time": 5.0},
                            "children": [
                                {
                                    "name": "plugh",
                                    "metrics": {"time (inc)": 5.0, "time": 5.0},
                                },
                                {
                                    "name": "xyzzy",
                                    "metrics": {"time (inc)": 25.0, "time": 5.0},
                                    "children": [
                                        {
                                            "name": "thud",
                                            "metrics": {
                                                "time (inc)": 25.0,
                                                "time": 5.0,
                                            },
                                            "children": [
                                                {
                                                    "name": "baz",
                                                    "metrics": {
                                                        "time (inc)": 5.0,
                                                        "time": 5.0,
                                                    },
                                                },
                                                {
                                                    "name": "garply",
                                                    "metrics": {
                                                        "time (inc)": 15.0,
                                                        "time": 15.0,
                                                    },
                                                },
                                            ],
                                        }
                                    ],
                                },
                            ],
                        },
                        {
                            "name": "garply",
                            "metrics": {"time (inc)": 15.0, "time": 15.0},
                        },
                    ],
                },
            ],
        },
        {
            "name": "waldo",
            "metrics": {"time (inc)": 30.0, "time": 10.0},
            "children": [
                {
                    "name": "bar",
                    "metrics": {"time (inc)": 20.0, "time": 5.0},
                    "children": [
                        {"name": "baz", "metrics": {"time (inc)": 5.0, "time": 5.0}},
                        {
                            "name": "grault",
                            "metrics": {"time (inc)": 10.0, "time": 10.0},
                        },
                    ],
                }
            ],
        },
    ]

    return graph_dict

In [3]:
gf = ht.GraphFrame.from_literal(mock_graph_literal())

In [4]:
print(gf.tree(color=True, metric="time"))
gf.dataframe

0.000 foo
├─ 5.000 bar
│  ├─ 5.000 baz
│  └─ 10.000 grault
├─ 0.000 qux
│  └─ 5.000 quux
│     └─ 10.000 corge
│        ├─ 5.000 bar
│        │  ├─ 5.000 baz
│        │  └─ 10.000 grault
│        ├─ 10.000 grault
│        └─ 15.000 garply
└─ 0.000 waldo
   ├─ 5.000 fred
   │  ├─ 5.000 plugh
   │  └─ 5.000 xyzzy
   │     └─ 5.000 thud
   │        ├─ 5.000 baz
   │        └─ 15.000 garply
   └─ 15.000 garply
10.000 waldo
└─ 5.000 bar
   ├─ 5.000 baz
   └─ 10.000 grault

                      name  time (inc)  time
node
{'name': 'foo'}        foo       130.0   0.0
{'name': 'bar'}        bar        20.0   5.0
{'name': 'baz'}        baz         5.0   5.0
{'name': 'grault'}  grault        10.0  10.0
{'name': 'qux'}        qux        60.0   0.0
{'name': 'quux'}      quux        60.0   5.0
{'name': 'corge'}    corge        55.0  10.0
{'name': 'bar'}        bar        20.0   5.0
{'name': 'baz'}        baz         5.0   5.0
{'name': 'grault'}  grault        10.0  10.0
{'name': 'garply'}  garply        15.0  15.0
{'name': 'grault'}  grault        10.0  10.0
{'name': 'waldo'}    waldo        50.0   0.0
{'name': 'fred'}      fred        35.0   5.0
{'name': 'plugh'}    plugh         5.0   5.0
{'name': 'xyzzy'}    xyzzy        25.0   5.0
{'name': 'thud'}      thud        25.0   5.0
{'name': 'baz'}        baz         5.0   5.0
{'name': 'garply'}  garply        15.0  15.0
{'name': 'garply'}  garply        15.0  15.0
{'name': 'waldo'}    waldo        30.0  10.0
{'name': 'bar'}        bar        20.0   5.0
{'name': 'baz'}        baz         5.0   5.0
{'name': 'grault'}  grault        10.0  10.0

### Query 0
Testing depth query

In [5]:
ktTree = [
        {
            "name": "A",
            "metrics": {"time (inc)": 130.0, "time": 0.0},
            "children": [
                {
                    "name": "B",
                    "metrics": {"time (inc)": 20.0, "time": 5.0},
                    "children": [
                        {"name": "D", "metrics": {"time (inc)": 5.0, "time": 5.0}},
                        {
                            "name": "E",
                            "metrics": {"time (inc)": 10.0, "time": 10.0},
                        },
                    ],
                },
                {
                    "name": "C",
                    "metrics": {"time (inc)": 20.0, "time": 5.0},
                    "children": [
                        {"name": "F", "metrics": {"time (inc)": 5.0, "time": 5.0}},
                        {
                            "name": "G",
                            "metrics": {"time (inc)": 10.0, "time": 10.0},
                        },
                    ],
                },
            ],
        }
]

kt = ht.GraphFrame.from_literal(ktTree)
print(kt.tree())

0.000 A
├─ 5.000 B
│  ├─ 5.000 D
│  └─ 10.000 E
└─ 5.000 C
   ├─ 5.000 F
   └─ 10.000 G

In [6]:
def match_depth(row):
    if row.name._depth <= 1:
        return True
    return False
from hatchet import QueryMatcher
query = QueryMatcher().match("*", match_depth)

newgf = kt.filter(query, squash=True) #gets A,B,C

#Get B, D, E

print(newgf.tree())

ImportError: cannot import name 'QueryMatcher' from 'hatchet' (/usr/local/lib/python3.7/site-packages/hatchet/__init__.py)

In [25]:
def match_depth(row, startDepth, endDepth):
    if row.name._depth <= endDepth and row.name._depth >= startDepth:
        return True
    return False
from hatchet import QueryMatcher
query = QueryMatcher().match("*", match_depth(1,3))

newgf = kt.filter(query, squash=True) #gets A,B,C

#Get B, D, E

print(newgf.tree())

TypeError: match_depth() missing 1 required positional argument: 'endDepth'

### Query 1
This query matches the following:
1. A single node with name "qux"
2. 0 or more nodes with inclusive time greater than 10
3. A single node with name starting with "gr" and inclusive time less than or equal to 10

In [5]:
query = [
    {"name": "qux"},
    ("*", {"time (inc)": "> 10"}),
    {"name": "gr[a-z]+", "time (inc)": "<= 10"}
]

In [6]:
from IPython.display import display, HTML
sgf = gf.filter(query, squash=True)
#print(sgf.tree(color=True, metric="time (inc)"))
display(HTML(sgf.dataframe.to_html()))

In [24]:
# Query Katy 
# Goal: get qux and all of its children
"""
├─ 60.000 qux
│  └─ 60.000 quux
│     └─ 55.000 corge
│        ├─ 20.000 bar
│        │  ├─ 5.000 baz
│        │  └─ 10.000 grault
│        ├─ 15.000 garply
│        └─ 10.000 grault
"""
# find node "qux" then continue downstream and select all nodes
# query = [
#     {"name": "qux"},
#     "*",
#     {"name": "grault"}
# ]
query = [
    {"name": "foo"},
    "*",
    {"name": "waldo"}
]
# DOES NOT WORK: find node qux through depth = {bar, garply, grault} (NO baz and grault)
# query = [
#     {"name" : "qux"},
#     "*",
#     {"name" : "garply"}
# ]
sgf = gf.filter(query, squash=True)
display(HTML(sgf.dataframe.to_html()))

In [8]:
from IPython.display import display, HTML
sgf = gf.filter(query, squash=True)
display(HTML(sgf.dataframe.to_html()))

### Query 2
This query matches the following:
1. A single node with name "bar"
2. 0 or more nodes with inclusive time greater than 50
3. A single node with name starting with "gr" and inclusive time less than or equal to 10

In [12]:
query = [
    {"name": "bar"},
    ("*", {"time (inc)": "> 50"}),
    {"name": "gr[a-z]+", "time (inc)": "<= 10"}
]

In [13]:
sgf = gf.filter(query, squash=True)
print(sgf.tree(color=True, metric="time (inc)"))
sgf.dataframe

    __          __       __         __
   / /_  ____ _/ /______/ /_  ___  / /_
  / __ \/ __ `/ __/ ___/ __ \/ _ \/ __/
 / / / / /_/ / /_/ /__/ / / /  __/ /_
/_/ /_/\__,_/\__/\___/_/ /_/\___/\__/  v1.2.0

45.000 bar
└─ 30.000 grault

Legend (Metric: time (inc))
█ 40.50 - 45.00
█ 31.50 - 40.50
█ 22.50 - 31.50
█ 13.50 - 22.50
█ 4.50 - 13.50
█ 0.00 - 4.50

name User code    ◀  Only in left graph    ▶  Only in right graph

                      name  time (inc)  time
node
{'name': 'bar'}        bar        45.0  15.0
{'name': 'grault'}  grault        30.0  30.0

### Query 3

This query matches the following:
1. A single node with name "waldo"
2. 1 or more of any node
3. A single node with an inclusive time >= 20
4. 1 or more of any node
5. A single node with an exclusive and inclusive time equal to 5

In [14]:
query = [
    {"name": "waldo"},
    "+",
    {"time (inc)": ">= 20.0"},
    "+",
    {"time (inc)": 5.0, "time": 5.0}
]

In [15]:
sgf = gf.filter(query, squash=True)
print(sgf.tree(color=True, metric="time (inc)"))
sgf.dataframe

    __          __       __         __
   / /_  ____ _/ /______/ /_  ___  / /_
  / __ \/ __ `/ __/ ___/ __ \/ _ \/ __/
 / / / / /_/ / /_/ /__/ / / /  __/ /_
/_/ /_/\__,_/\__/\___/_/ /_/\___/\__/  v1.2.0

20.000 waldo
└─ 20.000 fred
   └─ 15.000 xyzzy
      └─ 10.000 thud
         └─ 5.000 baz

Legend (Metric: time (inc))
█ 18.00 - 20.00
█ 14.00 - 18.00
█ 10.00 - 14.00
█ 6.00 - 10.00
█ 2.00 - 6.00
█ 0.00 - 2.00

name User code    ◀  Only in left graph    ▶  Only in right graph

                    name  time (inc)  time
node
{'name': 'waldo'}  waldo        20.0   0.0
{'name': 'fred'}    fred        20.0   5.0
{'name': 'xyzzy'}  xyzzy        15.0   5.0
{'name': 'thud'}    thud        10.0   5.0
{'name': 'baz'}      baz         5.0   5.0

### Query 4

This query matches the following:
1. 0 or more nodes
2. A single node with name "bar"
3. 0 or more nodes

In [16]:
query = [
    "*",
    {"name": "bar"},
    "*"
]

In [17]:
sgf = gf.filter(query, squash=True)
print(sgf.tree(color=True, metric="time (inc)"))
sgf.dataframe

    __          __       __         __
   / /_  ____ _/ /______/ /_  ___  / /_
  / __ \/ __ `/ __/ ___/ __ \/ _ \/ __/
 / / / / /_/ / /_/ /__/ / / /  __/ /_
/_/ /_/\__,_/\__/\___/_/ /_/\___/\__/  v1.2.0

55.000 foo
├─ 20.000 bar
│  ├─ 5.000 baz
│  └─ 10.000 grault
└─ 35.000 qux
   └─ 35.000 quux
      └─ 30.000 corge
         └─ 20.000 bar
            ├─ 5.000 baz
            └─ 10.000 grault
30.000 waldo
└─ 20.000 bar
   ├─ 5.000 baz
   └─ 10.000 grault

Legend (Metric: time (inc))
█ 49.50 - 55.00
█ 38.50 - 49.50
█ 27.50 - 38.50
█ 16.50 - 27.50
█ 5.50 - 16.50
█ 0.00 - 5.50

name User code    ◀  Only in left graph    ▶  Only in right graph

                      name  time (inc)  time
node
{'name': 'foo'}        foo        55.0   0.0
{'name': 'bar'}        bar        20.0   5.0
{'name': 'baz'}        baz         5.0   5.0
{'name': 'grault'}  grault        10.0  10.0
{'name': 'qux'}        qux        35.0   0.0
{'name': 'quux'}      quux        35.0   5.0
{'name': 'corge'}    corge        30.0  10.0
{'name': 'bar'}        bar        20.0   5.0
{'name': 'baz'}        baz         5.0   5.0
{'name': 'grault'}  grault        10.0  10.0
{'name': 'waldo'}    waldo        30.0  10.0
{'name': 'bar'}        bar        20.0   5.0
{'name': 'baz'}        baz         5.0   5.0
{'name': 'grault'}  grault        10.0  10.0

### Query 5

This query matches the following:
1. A single node with name "waldo"
2. 1 or more of any node
3. A single node with an inclusive time >= 20
4. 1 or more of any node
5. A single node with an exclusive and inclusive time equal to 7.5

This query does not match any node. It should raise an `EmptyFilter` exception.

In [ ]:
query = [
    {"name": "waldo"},
    "+",
    {"time (inc)": ">= 20.0"},
    "+",
    {"time (inc)": 7.5, "time": 7.5}
]

In [ ]:
sgf = gf.filter(query, squash=True)
print(sgf.tree(color=True, metric="time (inc)"))
sgf.dataframe

## "Real-Life" Example

This example uses the `asde/hatchet-sc19-datasets/kripke-mpi/mvapich2.3/hpctoolkit-kripke-database-2589460` database from the SC19 paper.

In [30]:
gf = ht.GraphFrame.from_hpctoolkit("/usr/workspace/wsb/asde/hatchet-sc19-datasets/kripke-mpi/mvapich2.3/hpctoolkit-kripke-database-2589460")

--------------------------------------------------------------------------------
Error: Shared object (.so) not found for cython module.
	Please run install.sh from the hatchet root directory to build modules.
--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/Users/katywilliams/GitHub/hatchet-katy/hatchet/query_lang/hatchet/hatchet/readers/hpctoolkit_reader.py", line 24, in <module>
    import hatchet.cython_modules.libs.subtract_metrics as smc
ModuleNotFoundError: No module named 'hatchet.cython_modules.libs.subtract_metrics'

ModuleNotFoundError: No module named 'hatchet.cython_modules.libs.subtract_metrics'

In [ ]:
gf.drop_index_levels()

In [ ]:
print(gf.tree(color=True, metric="time (inc)"))
gf.dataframe

### Query 1

This query will match all paths from root(s) to leaves that contains an MPI node (function that starts with "MPI_" or "PMPI_".

In [ ]:
query = [
    "*",
    {"name": "P?MPI_.*"},
    "*"
]

In [ ]:
sgf = gf.filter(query, squash=True)
print(sgf.tree(color=True, metric="time (inc)"))
sgf.dataframe

### Query 2

This query will find all paths within the DAG that starts with a MPI node and ends with a MPID node.

_Note: the MPID node filter starts with "[0-9]*:?" because the MPID nodes in the DAG seem to start with some type of identifier that consists of a number followed by a colon. This prefix to the regex string is added to effectively ignore this indentifier._

In [ ]:
query = [
    {"name": "P?MPI_.*"},
    "*",
    {"name": "[0-9]*:?MPID_.*"}
]

In [ ]:
sgf = gf.filter(query, squash=True)
print(sgf.tree(color=True, metric="time (inc)"))
sgf.dataframe

### Query 3

This query finds all paths from root(s) to leaves that contains a Kripke "Kernel" call that calls a Kripke "Loop" function.

In [ ]:
query = [
    "*",
    {"name": "Kernel.*"},
    "*",
    {"name": "Loop.*"},
    "*"
]

In [ ]:
sgf = gf.filter(query, squash=True)
print(sgf.tree(color=True, metric="time (inc)"))
sgf.dataframe

### Query 4

This query finds all subtrees rooted on calls to a Kripke "Kernel" function and containing only nodes with an inclusive time greater than 5000.

In [ ]:
query = [
    {"name": "Kernel.*"},
    ("*", {"time (inc)": "> 5000"})
]

In [ ]:
sgf = gf.filter(query, squash=True)
print(sgf.tree(color=True, metric="time (inc)"))
sgf.dataframe

### Query 5

This query uses the low-level Query Language API to find all subtrees rooted at MPI nodes and ending with calls to Infiniband Verbs, Mellanox interconnect driver, or Intel Omni-Path interconnect driver functions.

This query does not (seem to) contain any low-level networking library calls, so it should raise an `EmptyFilter` exception.

In [ ]:
# Matches MPI function calls
def match_mpi(node):
    if node["name"].startswith("MPI_") or node["name"].startswith("PMPI_"):
        return True
    return False

# Matches Infiniband Verbs, Mellanox interconnect driver, or Omni-Path interconnect driver function calls
def match_ibv_mlx_or_omgt(node):
    if node["name"].startswith("ibv") or node["name"].startswith("mlx") or node["name"].startswith("omgt"):
        return True
    return False

query = ht.QueryMatcher().match(filter_func=match_mpi).rel("*").rel(filter_func=match_ibv_mlx_or_omgt)

In [ ]:
sgf = gf.filter(query, squash=True)
print(sgf.tree(color=True, metric="time (inc)"))
sgf.dataframe